language: c
sudo: false
env:
  global:
    - SNAPSHOT_VERSION: 'lts-7.2'
    - GHC_VERSION: '8.0.1'
    - STACK_RELEASE: 'https://github.com/commercialhaskell/stack/releases/download/v1.2.0/stack-1.2.0-linux-x86_64.tar.gz'

sudo: false
cache:
  directories:
  - $HOME/.stack/snapshots/x86_64-linux/$SNAPSHOT_VERSION/$GHC_VERSION/

before_install:
  - ls $HOME/.stack/snapshots/x86_64-linux/$SNAPSHOT_VERSION/
  - ls $HOME/.stack/snapshots/x86_64-linux/$SNAPSHOT_VERSION/$GHC_VERSION/
  - mkdir -p $HOME/bin
  - curl -L "$STACK_RELEASE" | tar -C "$HOME/bin" --strip=1 -xzf - stack-1.2.0-linux-x86_64/stack
  - chmod +x $HOME/bin/stack

install:
  - ls $HOME/.stack/snapshots/x86_64-linux/$SNAPSHOT_VERSION/
  - ls $HOME/.stack/snapshots/x86_64-linux/$SNAPSHOT_VERSION/$GHC_VERSION/
  - stack setup
  - stack test --only-snapshot

script:
  - stack test
