language: haskell
ghc:
  - '7.8'

sudo: false
cache:
  directories:
  - $HOME/.stack/snapshots/x86_64-linux/nightly-2015-06-12/7.10.1/

before_install:
  - ls $HOME/.stack/snapshots/x86_64-linux/nightly-2015-06-12/
  - ls $HOME/.stack/snapshots/x86_64-linux/nightly-2015-06-12/7.10.1/
  - git clone https://github.com/commercialhaskell/stack
  - cabal sandbox init
  - cabal sandbox add-source stack
  - cabal install stack
  - mkdir $HOME/bin
  - cp .cabal-sandbox/bin/stack $HOME/bin

install:
  - ls $HOME/.stack/snapshots/x86_64-linux/nightly-2015-06-12/
  - ls $HOME/.stack/snapshots/x86_64-linux/nightly-2015-06-12/7.10.1/
  - stack setup
  - stack test --only-snapshot

script:
  - stack test
